Repository inspectIT/inspectit-ocelot, pull requests merged in 2021-06, with the labels that each got.

#1095 Allow disabling console log on start-up
  inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/logging/logback/LogbackInitializer.java
  inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/logging/logback/LogbackInitializerTest.java
Labels: area/agent, enhancement

#1119 Prevent agent command handler from continuously sending requests in live mode
  inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/command/CommandHandler.java
Labels: area/agent, bug

#1120 Visual editor shows existing properties in case configuration is empty
  components/inspectit-ocelot-configurationserver-ui/src/components/editor/EditorView.js
Labels: area/config-ui, bug
