Repository inspectIT/inspectit-ocelot, pull requests merged in 2021-04, with the labels that each got.

#1039 Publish agent, test with https://jitpack.io/
  inspectit-ocelot-agent/build.gradle
  inspectit-ocelot-config/build.gradle
  inspectit-ocelot-sdk/build.gradle
Labels: area/general

#1053 Fix CannotStubVoidMethodWithReturnValue
  inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/SpringTestBase.java
Labels: area/agent, bug

#1062 Extending EUM server to enrich received spans with additional tags
  components/inspectit-ocelot-eum-server/src/main/java/io/opentelemetry/sdk/trace/OcelotSpanUtils.java
  components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/beacon/processor/ClientHeaderBeaconProcessor.java
  components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/EumExportersSettings.java
  components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/configuration/model/EumTraceExportersSettings.java
  components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/tracing/opentelemtry/OpenTelemetryProtoConverter.java
  components/inspectit-ocelot-eum-server/src/main/java/rocks/inspectit/oce/eum/server/utils/RequestUtils.java
  components/inspectit-ocelot-eum-server/src/main/resources/application.yml
  components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/rest/TraceControllerIntTest.java
  components/inspectit-ocelot-eum-server/src/test/java/rocks/inspectit/oce/eum/server/tracing/opentelemtry/OpenTelemetryProtoConverterTest.java
  inspectit-ocelot-documentation/docs/enduser-monitoring/eum-server-configuration.md
Labels: area/eum-server, enhancement
