Repository inspectIT/inspectit-ocelot, pull requests merged in 2022-05, with the labels that each got.

#1410 Remove OpenCensus library from OpenAPM landscapes
  inspectit-ocelot-documentation/docs/assets/demo-landscape-influxdb-jaeger.png
  inspectit-ocelot-documentation/docs/assets/demo-landscape-influxdb-zipkin.png
  inspectit-ocelot-documentation/docs/assets/demo-landscape-prometheus-jaeger.png
  inspectit-ocelot-documentation/docs/assets/inspectit-ocelot-landscape.png
  inspectit-ocelot-documentation/docs/getting-started/docker-examples.md
  inspectit-ocelot-documentation/docs/hello-world.md
Labels: area/documentation

#1412 Replace Wavefront instructions with collection of additional scenarios in Docs
  inspectit-ocelot-documentation/docs/getting-started/docker-examples.md
Labels: area/documentation

#1414 Fix default config for JDBC scopes
  inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/scopes/db/jdbc.yml
Labels: bug

#1432 Ability to use 64 bit trace IDs
  inspectit-ocelot-config/src/main/java/rocks/inspectit/ocelot/config/model/tracing/TracingSettings.java
  inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/basics.yml
  inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/instrumentation/context/ContextPropagationUtil.java
  inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/OpenTelemetryControllerImpl.java
  inspectit-ocelot-core/src/main/java/rocks/inspectit/ocelot/core/opentelemetry/trace/CustomIdGenerator.java
  inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/opentelemetry/OpenTelemetryControllerImplIntTest.java
  inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/opentelemetry/OpenTelemetryControllerImplTest.java
  inspectit-ocelot-core/src/test/java/rocks/inspectit/ocelot/core/opentelemetry/trace/CustomIdGeneratorTest.java
  inspectit-ocelot-documentation/docs/tracing/tracing.md
Labels: enhancement, area/agent

#1448 Use correct request method in span names for httpconnection
  inspectit-ocelot-config/src/main/resources/rocks/inspectit/ocelot/config/default/instrumentation/actions/http/httpurlconnection.yml
Labels: bug, area/agent
